### ISSUE TITLE
?Wordle providing incorrect results

### ISSUE THREAD

**Issue by ILiedAboutCake** [johnpyp/mini-me#6] opened 2022-05-11 13:59 UTC
I believe this bug was introduced by #2 using a static list of words. Since then the New York Times bought the Wordle project and removed certain words from it's static list.

wordls.rs should be updated to reflect the NYTimes changes.

**Comment by johnpyp** [comment] 2022-05-11 15:27
Looks like @JordanDeBeer didn't properly account for regressions. I'm sure this was in the interest of speed and customer obsession, but this should be addressed ASAP.

@JordanDeBeer can you fix this and create an SOP for updating in the future?

**Comment by elements-ix** [comment] 2022-05-11 21:02
Do we have any metrics around how many customers this is impacting? We should escalate to P1 if it's serious.

**Comment by JordanDeBeer** [comment] 2022-05-11 21:09
In order to provide this work under a new SOW, I'll need approximately $10,000 USD in a timely manner. I am dependable to provide the effort.

**Comment by johnpyp** [comment] 2022-05-11 21:12
As this discussion has become hostile and unproductive, closing and locking. Please follow-up on alternative channels if you're looking for prioritization on this issue.

**Closed as completed by johnpyp** 2022-05-11 21:12 UTC
